// swift-tools-version: 6.0
import PackageDescription

// Meridian — SwiftPM manifest.
//
// The shipping project is generated by XcodeGen from `project.yml` (three targets:
// the iOS app, the WidgetKit/ActivityKit extension, and the watchOS app). SwiftPM
// cannot model app-extension or watch-app product types, so this manifest exists
// only as a convenience for command-line builds and for editors/tooling that index
// the app sources. The widget and watch targets are NOT represented here — generate
// the Xcode project with `xcodegen generate` to build all three.
//
// GeoPlaceRepository uses the system SQLite via the `SQLite3` module map, so no SPM
// package dependency is required — only the `sqlite3` system library is linked.

let package = Package(
    name: "Meridian",
    platforms: [
        .iOS(.v26) // SwiftPM tools cap at .v26; the shipping deployment target is iOS 27 (set in project.yml).
    ],
    products: [
        .executable(name: "MeridianApp", targets: ["MeridianApp"])
    ],
    targets: [
        .executableTarget(
            name: "MeridianApp",
            path: ".",
            exclude: [
                "project.yml",
                "README_iOS.md",
                "Package.swift",
                "MeridianWidget",
                "MeridianWatch"
            ],
            sources: [
                "MeridianApp",
                "Shared/SharedModels.swift",
                "Shared/EventCountdownAttributes.swift"
            ],
            resources: [
                .process("MeridianApp/Resources")
            ],
            linkerSettings: [
                .linkedLibrary("sqlite3")
            ]
        )
    ]
)
