// ScrubberGlass.swift
// Meridian — iOS 27 / Swift 6
//
// Ported from app/src/main/java/com/example/core/designsystem/ScrubberGlass.kt
//
// NOTE ON OWNERSHIP: the canonical `ScrubberGlass` enum and `ScrubberGlassAlphas`
// struct already live in `DesignSystem/Theme.swift` (generated by the theme owner)
// with a byte-identical recipe:
//
//   struct ScrubberGlassAlphas { pillTint; cardTint; trackBackground; frosted }
//   enum ScrubberGlass {
//       static func alphas(opacity: Double) -> ScrubberGlassAlphas
//       static func fraction(_ opacity: Double) -> Double   // (o-0.10)/(1.0-0.10), clamped
//   }
//
// Re-declaring those types here would be a redeclaration error, so this file does
// NOT redefine them. The bottom accessory and other design-system consumers call
// `ScrubberGlass.alphas(opacity:)` from Theme.swift directly. The mapping matches
// Android exactly: `t = fraction(opacity)` where opacity is the normalized
// glass-opacity fraction (0.10…1.0, = Android percent/100), with floors
// pill 0.66→1.0, card 0.86→1.0, track 0.22→0.46, frosted when t ≥ 0.03.
//
// This file is intentionally minimal to preserve the assigned file slot without
// introducing a duplicate symbol. If the Theme.swift copy is ever removed, restore
// the full implementation here (see git history of the ds-new task).

import Foundation

// Intentionally empty: see note above. `ScrubberGlass` / `ScrubberGlassAlphas` are
// declared in Theme.swift.
